name: Deploy to GitHub Pages

on:
   push:
     branches:
       - master  

jobs:
   build:
     runs-on: ubuntu-latest

     steps:
       - name: Checkout repository
         uses: actions/checkout@v2

       - name: Set up JDK 17
         uses: actions/setup-java@v2
         with:
           distribution: 'adopt'
           java-version: '17'

       - name: Build Spring Boot Project
         run: mvn clean package

       - name: Copy HTML files to publish dir
         run: mkdir -p ./target/classes/templates/pages && cp -R ./target/*.html ./target/classes/templates/pages/

       - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./target/classes/templates/pages
