name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build Spring Boot Project
      run: mvn clean package

    - name: Create publish directory
      run: mkdir -p ./target/classes/templates/pages

    - name: Verify target and index.html presence
      run: |
        if [ -d ./target ]; then echo "target directory exists"; else echo "target directory does NOT exist"; fi
        if [ -f index.html ]; then echo "index.html found at root"; else echo "index.html NOT found at root"; fi

    - name: Copy index.html
      run: |
        cp index.html ./target/classes/templates/pages/
        if [ -f ./target/classes/templates/pages/index.html ]; then echo "index.html successfully copied"; else echo "index.html copy failed"; fi

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/classes/templates/pages
        publish_branch: master
